// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0f8LKWgEwzJg4q3taFAmIj56NjTyvJwI',
    appId: '1:802320953608:web:30ce5d2b911dfb2cfebcbd',
    messagingSenderId: '802320953608',
    projectId: 'flutter-community-ibague',
    authDomain: 'flutter-community-ibague.firebaseapp.com',
    storageBucket: 'flutter-community-ibague.appspot.com',
    measurementId: 'G-7Q25N22DJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-4Rf591Uo2A0tjIXBAOrTYN96ATkCkWU',
    appId: '1:802320953608:android:4011820edbcde49afebcbd',
    messagingSenderId: '802320953608',
    projectId: 'flutter-community-ibague',
    storageBucket: 'flutter-community-ibague.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjxoxwiysWIA-VjM9WBqjxezmTcuq5Kt0',
    appId: '1:802320953608:ios:7a2ae229cefd9827febcbd',
    messagingSenderId: '802320953608',
    projectId: 'flutter-community-ibague',
    storageBucket: 'flutter-community-ibague.appspot.com',
    iosBundleId: 'flutter.community.ibague.flutterCommunityIbague',
  );
}
